FROM golang:1.22-alpine AS builder
WORKDIR /backend
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o api ./cmd/api


FROM alpine:3.20.0
COPY --from=builder /backend/api /app/
WORKDIR /app

EXPOSE 8080
CMD ["./api"]