name: Deploy to VPS

on:
  push:
    branches: ['main']

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ['backend', 'frontend', 'proxy']
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:{{ matrix.context }}'
          push: true
          tags: leogues/music-hub-${{ matrix.context }}:latest, leogues/music-hub-${{ matrix.context }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_vps:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          script: |
            cd ../srv/musichub
            chmod +x deploy-script
            ./deploy-script
